# Generated by Django 5.1.2 on 2024-10-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('complit', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
